### ISSUE TITLE
Rate method Logic issue

### ISSUE THREAD

**Issue by habenhadush** [ardalis/SolidSample#10]
![from_course](https://github.com/ardalis/SolidSample/assets/74584157/9bafc827-f43f-4095-999a-1cd013c2520b)
![suggestion](https://github.com/ardalis/SolidSample/assets/74584157/4d891a45-2baf-4e0d-ba59-d2bed65b75b1)

Hello,

I think the logic of the <code> Rate(Policy policy) </code> will be 900m even if  the <code>policy.Deductible < 500</code>.

**Comment by ardalis** [comment]
Ah, good catch. Probably there should be a unit test that verifies that behavior didn't regress. :)
