### ISSUE TITLE
DIP Sample End State?

### ISSUE THREAD

**Issue by ardalis** [ardalis/SolidSample#2]
In the Pluralsight feedback channel someone reported that I didn't show/have the final DIP samples here. Need to confirm.

**Comment by Ravindra-J** [comment]
Hi @ardalis  I have just downloaded the zip file and still cannot see the final version of SOLID applied code in it. could you please help me out

**Comment by ardalis** [comment]
I think the 'current' branch has the latest. Can you look here and confirm if you have what you need? @Ravindra-J 

https://github.com/ardalis/SolidSample/tree/current/ArdalisRating

Thanks!

**Comment by Ravindra-J** [comment]
yes @ardalis current branch has what i am looking for. thank you :)

**Comment by ardalis** [comment]
Great, thanks!
