### ISSUE TITLE
RaterFactory Issue

### ISSUE THREAD

**Issue by JonesZack** [ardalis/SolidSample#3]
I'm working through the course and am stuck in the RaterFactory portion of OCP. In the Demo: Applying OCP to ReatingEngine at 3:42 there you can see the project explorer but there doesn't seem to be a Rater class shown. I've followed your code as best I can but I'm getting the "Rater" class or type could not be found error. Given that there's no Rater class in the solution explorer I don't think I'm supposed to create one. Is it defined within the RaterFactory class? Thanks in advance for your help.

**Comment by ardalis** [comment]
Hi! The code you want isn't shown in the video, but is in the sample code here. You just have to use the branch dropdown to select the module you're looking for. Here's the Rater class in the OCP branch:
https://github.com/ardalis/SolidSample/blob/OCP/ArdalisRating/Rater.cs

**Comment by ardalis** [comment]
Here's the dropdown:
![image](https://user-images.githubusercontent.com/782127/84562752-eaec3d00-ad24-11ea-8522-48244aa5e7d3.png)

**Comment by JonesZack** [comment]
Thank you sir! I have working now. I learned something about Git as well.
